### ISSUE TITLE
timestamp convention and coordinate frame?

### ISSUE THREAD

**Issue by knelk** [uzh-rpg/eds-buildconf#7]
Thanks for the great work!

1) Timestamps: Do you still need to apply ``timeshift_cam_imu: -0.005475324106170151`` and ``timeshift_cam_imu: 0.0016611976654922291`` to the timestamps of RGB and event camera timestamps? Are the MotionCapture-poses in IMU time (or in event time? or in RGB time?)? 

2) Poses: Are the poses in the rgb frame, in the event frame or in the imu frame?

**Comment by jhidalgocarrio** [comment]
Hi,

This question is concerning the EDS dataset published [here](https://rpg.ifi.uzh.ch/eds.html#dataset)

1. The timeshift needs to be applied to the IMU values. The IMU data is the IMU equipped in the Prophesse event camera, this is why the timeshift is smaller for the event camera timestamps.  The values timeshift_cam_imu: are estimated by Kalibr and are in [results](https://download.ifi.uzh.ch/rpg/eds/dataset/16_calibration/01_calib/01_calib_results.zip)

2. The motion capture system has its own timestamps and the frame of coordinate is the event camera. A hand_eye calibration from the Motion capture markers to the event camera frame (reconstructed frames from events) was computed (this is a fixed transformation). Such transformation is already applied to the Motion capture poses in order to have it at the beamsplitter optical axis.

**Comment by knelk** [comment]
Thanks for the reply.

Ok got it, event camera and rgb use the same clock. 

>  The motion capture system has its own timestamps

How can we time-synchronize the motion-capture timestamps to the camera timestamps then? Or how was it done? (it seems to be done already) did you use imu´s angular velocities?

> from the Motion capture markers to the event camera frame (reconstructed frames from events) was computed (this is a fixed transformation). Such transformation is already applied to the Motion capture poses

So to get the pose of the rgb-camera (T_world_rgb), we would then need to apply  T_world_rgb = T_world_event @ T_ev_rgb, correct?

**Comment by jhidalgocarrio** [comment]
>How can we time-synchronize the motion-capture timestamps to the camera timestamps then? Or how was it done? (it seems to be done already)

In principle, you don't have to do anything. The Motion capture poses are recorded at a high timestamp frequency (the highest frequency [possible](https://www.rock-robotics.org/documentation/data_processing/timestamping.html)). The reason why I used [RTT/Rock](https://www.orocos.org/rtt/) is to have real-time logging capabilities.

> did you use imu´s angular velocities?

No, how would you use them? Do you mean angular velocity integration to get orientation in a KF manner?

>So to get the pose of the rgb-camera (T_world_rgb), we would then need to apply T_world_rgb = T_world_event @ T_ev_rgb, correct?

Yes, this is correct. However, I did  not do it because T_ev_rgb transformation (camera extrinsic) is rather small since in a beamsplitter setup the idea is to align both rectified cameras in a common optical axis (as much as possible):
```
	baseline T_1_0:
	 q: [-0.01158247  0.00713482 -0.00093424  0.99990703] +- [ 0.00164981  0.00061616  0.00013795]
	 t: [-0.00011239 -0.00059815 -0.00441668] +- [ 0.00044352  0.00043509  0.00182176]
```

**Comment by knelk** [comment]
> No, how would you use them? Do you mean angular velocity integration to get orientation in a KF manner?

For time-synchronization between recording device (cameras) and motion-capture sytem we used the recording time as an initial value (we are streaming Mocap poses to our recording setup). However, since this is not accurate yet, we did a refinement step by aligning the angular velocity of IMU with the angular velocity from motion-capture system (computed by central differences of pose estimates). See [figure 10 in tumvie](https://arxiv.org/pdf/2108.07329.pdf). 

AFACIT, RTT/Rock is basically using the recording time to do the time synchronization?

**Comment by jhidalgocarrio** [comment]
All right. I got it. This is a nice idea. I see in the [figure](https://arxiv.org/pdf/2108.07329.pdf) the Mocap angular velocities are not too noisy from the pose derivatives. 

> AFACIT, RTT/Rock is basically using the recording time to do the time synchronization?

Yes. I used the [stream aligner](https://www.rock-robotics.org/documentation/data_processing/stream_aligner.html) since most of the sensors (camera, IMU, Mocap) have a fixed sampling rate and latency can be estimated + RTT timestamp should be real-time. Events are synchro wrt the frames. The [e2calib](https://github.com/uzh-rpg/e2calib/blob/main/python/convert.py) H5 conversion checked for wrong timestamping and not a single event was out of timing.
Nevertheless, It would be also nice to have a figure similar to figure 10 in tumvie to double-check.

**Comment by knelk** [comment]
looks great to me (red is imu, blue mocap)

![image](https://user-images.githubusercontent.com/69507924/180230215-9d69d0ed-d0c4-45aa-8b81-f533176c608f.png)
![image](https://user-images.githubusercontent.com/69507924/180230372-6d121a13-b24e-479d-a578-5dcf7cab451d.png)
![image](https://user-images.githubusercontent.com/69507924/180230461-b2dbeede-acd6-4bca-ac1d-b0201d77a368.png)

**Comment by jhidalgocarrio** [comment]
That looks great!! @knelk 
Those are IMU angular velocities and computed angular velocities using central differences of GT pose. Right?
Do the two data stream timestamps  (IMU and GT) also look good, in your opinion?
Which sequence of the dataset are you showing in the figures?

**Comment by knelk** [comment]
>  Those are IMU angular velocities and computed angular velocities using central differences of GT pose. Right?

Yes

This is 11_all_characters, x-axis in seconds, y-axis in degrees/s. IMO it looks good, but not an expert with imus. Noticed a saturation in z-axis at 32secs
